### ISSUE TITLE
SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by RemiKalbe** [Cweili/svelte-fa#18]
I'm getting 
```js
/Users/remivillien/Git/RemiKalbe/dwoom-myaccount-frontend/node_modules/svelte-fa/src/fa.svelte:1
<script>
^

SyntaxError: Unexpected token <
    at Module._compile (internal/modules/cjs/loader.js:720:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/remivillien/Git/RemiKalbe/dwoom-myaccount-frontend/__sapper__/dev/server/index-f79d722d.js:11:26)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
> Server crashed
```

Using

```json
"sapper": "^0.27.9",
"svelte": "^3.12.1"
```

**Comment by nelsonpecora** [comment]
I'm getting the same issue (with rollup). It looks like `rollup-plugin-svelte` is configured correctly (using the default sapper config). @RemiKalbe were you able to figure out what was going on?

**Comment by RemiKalbe** [comment]
Sadly no, I don't believe it has anything to do with the library as I tested to create a small fontawesome component myself and I have the exact same issue. It must have something to do with the rollup config with sapper as it works on svelte.

**Comment by Cweili** [comment]
The [`main` field in `package.json`](https://github.com/Cweili/svelte-fa/blob/v2.0.2/package.json#L28) is a compiled common js file before `v2.1.0`. But it causes https://github.com/Cweili/svelte-fa/issues/15.

So I  set [`main` field to `.svelte` file](https://github.com/Cweili/svelte-fa/blob/v2.1.0/package.json#L28) as `svelte-virtual-list` does. https://github.com/sveltejs/svelte-virtual-list/blob/v3.0.1/package.json#L5

I'm not a `sapper` user. Anyone knows how to support both `sapper` project and pure `svelte` project? PRs welcome.

**Comment by RemiKalbe** [comment]
I asked the question to one of the maintainers of svelte/sapper, to use any component in sapper we have to install the component as a devDependencie.

**Comment by macsupport** [comment]
Works for me with sapper if I install like this: 

`npm install svelte-fa --save-dev`
