### ISSUE TITLE
Error: Not found: /fa.svelte

### ISSUE THREAD

**Issue by seriousm4x** [Cweili/svelte-fa#275]
When running in dev mode, I get the following error logged when reloading my page.

```
12:41:33 PM [vite-plugin-svelte] ssr compile done.
package         files     time     avg
frontend            2   23.9ms  12.0ms
Error: Not found: /fa.svelte
    at resolve (/node_modules/.pnpm/@sveltejs+kit@1.10.0_svelte@3.55.1+vite@4.1.4/node_modules/@sveltejs/kit/src/runtime/server/respond.js:394:13)
    at resolve (/node_modules/.pnpm/@sveltejs+kit@1.10.0_svelte@3.55.1+vite@4.1.4/node_modules/@sveltejs/kit/src/runtime/server/respond.js:243:5)
    at #options.hooks.handle (/node_modules/.pnpm/@sveltejs+kit@1.10.0_svelte@3.55.1+vite@4.1.4/node_modules/@sveltejs/kit/src/runtime/server/index.js:41:55)
    at Module.respond (/node_modules/.pnpm/@sveltejs+kit@1.10.0_svelte@3.55.1+vite@4.1.4/node_modules/@sveltejs/kit/src/runtime/server/respond.js:240:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

It all works, all icons show up and I can build my project without errors.

Imported as
```
import {
    faPowerOff,
    faEllipsisVertical,
    faCircle,
    faCircleUp,
    faCircleDown,
    faLock
} from '@fortawesome/free-solid-svg-icons';
import Fa from 'svelte-fa';
```

I've also tried explicitly importing svelte-fa (as the readme says) but the same error shows up.

Using `"@sveltejs/kit": "^1.10.0"` and `"svelte-fa": "^3.0.3"`

**Comment by Cweili** [comment]
Please provide a link to minimal reproduction.

**Comment by seriousm4x** [comment]
It randomly disappeared again and I can't reproduce it. I don't know what it was but I think everything is ok.
I'll report back and reopen if it happens again and I know how to reproduce it.
